# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "readprompt"
version = "1.0.0"
description = ""
readme = "README.md"
license = { file = "LICENSE" }
dependencies = []
